services:
  ollama:
    platform: linux/arm64
    extends:
      file: ollama/compose.yaml
      service: ollama

  webapp:
    platform: linux/arm64
    extends:
      file: webapp/compose.yaml
      service: webapp
    build:
      args:
        LLM_PROMPT_PRESET: "shakespearean english"
        PLATFORM: ${PLATFORM:-stm32mp257}

  zephyr:
    platform: linux/arm64
    extends:
      file: zephyr-application/compose.yaml
      service: zephyr
    build:
      args:
        PLATFORM: ${PLATFORM:-stm32mp257}
        REMOTEPROC: &remoteproc ${REMOTEPROC:-m33}
    annotations:
      remoteproc.name: *remoteproc

volumes:
  ollama-data:

# Topo-specific metadata
x-topo:
  name: "Lightbulb Moment"
  description: "Reads a switch over GPIO pins on an M class cpu, reports switch state over Remoteproc Message, then a web application on the A class reads this and displays a lightbulb in either the on or off state. The lightbulb state is described by an LLM in any user-specified style."
  features:
    - "remoteproc-runtime"
  args:
    PLATFORM:
      required: true
      description: The platform to build for. Must be either `stm32mp257` or `imx93`.
    REMOTEPROC:
      required: true
      description: The remoteproc device to use. Must be `m33` if the stm32 board is used, or `imx-rproc` if the imx93 board is used.
    LLM_PROMPT_PRESET:
      description: |
        The writing style for the LLM to use when generating messages about the light bulb state. Can be any style description (e.g., "shakespearean english", "pirate", "haiku", "detective noir").
      required: true
      example: "shakespearean english"
      default: "shakespearean english"
