# Used to produce dependency cache image in CI, to allow remote caching.
ARG BUILDPLATFORM

FROM --platform=${BUILDPLATFORM} ghcr.io/embeddedcontainers/zephyr:arm-0.17.4SDK AS deps

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install --no-install-recommends -y patch

WORKDIR /workdir

COPY west.yml manifest/west.yml

RUN west init -l manifest

RUN --mount=type=cache,target=/git-cache \
    west update --path-cache /git-cache --narrow -o=--depth=1

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r zephyr/scripts/requirements-base.txt jsonschema
